# DeepSeek API配置
deepseek:
  api:
    key: ${你的key}
    url: ${DEEPSEEK_API_URL:https://api.deepseek.com/v1/chat/completions}
# Kimi API配置
kimi:
  api:
    url: https://api.moonshot.cn/v1/chat/completions
    key: 你的key
